version: "3.8"
services:
  news:
    build:
      dockerfile: Dockerfile.dev
      context: "."
    volumes:
      - .:/news
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    container_name: container_db
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5436:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data